language: java
jdk:
  - oraclejdk8
notifications:
  - email: false
before_install:
  - cd java
jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy